Added assets dir
cloudposse/terraform-aws-ubuntu-assets-user-data pull request #1
Opened 2017-08-02 13:04 UTC by goruha

## What
* Added user data to add assets make targets

## Why
* We want assets to be backuped

2017-08-03 04:23 UTC, osterman commented on main.tf
> +    id = "${lower(format("%v-%v-%v-%v", var.namespace, var.stage, var.name, "assets"))}"
Why define a new `null_resource` when you can just use `tf_label` and append the specifier?

2017-08-03 04:37 UTC, osterman requested changes
See inline comment.

2017-08-04 09:16 UTC, goruha commented on main.tf
> +    id = "${lower(format("%v-%v-%v-%v", var.namespace, var.stage, var.name, "assets"))}"
It does not support 4 items in id

2017-08-04 09:17 UTC, goruha commented on main.tf
> +    id = "${lower(format("%v-%v-%v-%v", var.namespace, var.stage, var.name, "assets"))}"
It does not support 4 parts of id

2017-08-08 22:24 UTC, osterman commented on main.tf
> +    id = "${lower(format("%v-%v-%v-%v", var.namespace, var.stage, var.name, "assets"))}"
Overload the name. =)

2017-08-08 22:25 UTC, osterman commented on main.tf
> +    id = "${lower(format("%v-%v-%v-%v", var.namespace, var.stage, var.name, "assets"))}"
`name = "foo-something"`

2017-08-08 22:26 UTC, osterman commented on main.tf
> +    id = "${lower(format("%v-%v-%v-%v", var.namespace, var.stage, var.name, "assets"))}"
or better yet, let's add `attributes` as a new parameter to `tf_label` of type `list`. Use `join` to concatenate them with a `-`.

2017-08-09 18:04 UTC, osterman approved these changes

2017-08-09 18:15 UTC, merged