Migrate readme yaml
cloudposse/terraform-aws-ubuntu-assets-user-data pull request #5
Opened 2018-12-07 19:40 UTC by solairerove

## what
- regenerate readme md
- add description key in outputs values
- add makefile
- ignore harness
- prepare to open discussions on review

## why
- need to add categories and tags so we can pull them into the documentation

2018-12-07 19:40 UTC, solairerove commented
write plz necessary changes to add

2018-12-07 19:58 UTC, osterman commented on README.yaml
> +
Let's add related projects. List all the `user-data` modules as "related". See other readme yaml for example.

2018-12-07 19:59 UTC, osterman requested changes
Almost perfect. Add related modules. See comment.

2018-12-07 19:59 UTC, osterman commented on README.yaml
> +# How to use this project
Let's uncomment this and make a working example.

2018-12-10 04:06 UTC, osterman commented
Fix CI/CD

2018-12-10 04:06 UTC, osterman commented
![image](https://user-images.githubusercontent.com/52489/49710397-e86bcd00-fbed-11e8-9b6c-7fd18e50331c.png)


Run `terraform fmt` to fix

2018-12-10 12:35 UTC, solairerove commented
i ran `terraform fmt` but it is still failing

2018-12-10 22:59 UTC, osterman commented on docs/terraform.md
> +| policy_arn | description here |
"description here" does not count as a description =P

2018-12-10 22:59 UTC, osterman commented on outputs.tf
> +  description = "description here"
Saerch other modules for a better example of `user_data` description

2018-12-10 23:00 UTC, osterman commented on outputs.tf
> +  description = "description here"
Search other modules for a better example of `policy_arn` description

2019-01-05 14:39 UTC, solairerove commented
@osterman resolve review issues

2019-01-05 18:44 UTC, osterman commented on README.md
> +| policy_arn | IAM policy ARNы |
```suggestion
| policy_arn | IAM policy ARNs |
```

2019-01-05 18:44 UTC, osterman commented on docs/terraform.md
> +| policy_arn | IAM policy ARNы |
```suggestion
| policy_arn | IAM policy ARNs |
```

2019-01-05 18:44 UTC, osterman requested changes
See comments

2019-01-05 18:46 UTC, solairerove commented
@osterman 
fixed

2021-01-31 05:14 UTC, closed without merging